In [1]:
import pandas as pd
import numpy as np

# NORC

In [2]:
norc_raw = pd.read_csv("../data/raw-data/NORC/31122410.csv")

display(norc_raw)

,SU_ID,POLLCLOSE_STATE_WEIGHT,FINALVOTE_STATE_WEIGHT,POLLCLOSE_NATIONAL_WEIGHT,FINALVOTE_NATIONAL_WEIGHT,MODE,P_STATE,STATENUM,LVB,LIKELYVOTER,...,BORNAGAIN,BORNAGAINSTATE,ATTENDANCE,PARENTUS,CATOWNER,DOGOWNER,TIKTOKUSER,LGBT,HOUSING,SIZEPLACE
0,1000001,546.798136,0.357366,442.024098,0.250968,(2) Web,(HI) Hawaii,(11) Hawaii,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(2) No,(1) Yes,(1) Yes,(2) No,(2) Rented for cash,(2) Suburban
1,1000002,139.874024,0.231562,105.968208,0.076913,(2) Web,(ME) Maine,(21) Maine,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(2) No,(2) No,(2) No,(2) No,(2) Rented for cash,(3) Small town
2,1000003,1434.081847,1.508009,1274.137585,0.950696,(2) Web,(MN) Minnesota,(23) Minnesota,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(4) Rural
3,1000004,634.071275,0.380504,512.574504,0.267217,(2) Web,(HI) Hawaii,(11) Hawaii,(5) Already voted,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(2) Suburban
4,1000005,1.241451,0.001997,0.822831,0.000701,(2) Web,(NV) Nevada,(33) Nevada,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(2) Rented for cash,(3) Small town
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139933,1139934,494.636477,0.317270,365.905264,0.248358,(2) Web,(KY) Kentucky,(17) Kentucky,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(4) Rural
139934,1139935,902.328170,1.982933,725.383326,0.681543,(2) Web,(MT) Montana,(26) Montana,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(1) Yes,(1) Yes,(1) Yes,(1) Yes,(2) Rented for cash,(2) Suburban
139935,1139936,511.050649,0.450388,406.456748,0.282288,(2) Web,(AZ) Arizona,(4) Arizona,(1) Definitely will vote,(1) Likely voter,...,(1) Yes,(1) Yes,,(2) No,(2) No,(2) No,(1) Yes,(2) No,(1) Owned or being bought by you or someone in...,(1) Urban
139936,1139937,4832.216760,1.084959,3804.728285,2.281002,(2) Web,(AL) Alabama,(2) Alabama,(1) Definitely will vote,(1) Likely voter,...,,,(2) A few times a year or less,,,,,,(1) Owned or being bought by you or someone in...,(2) Suburban
139937,1139938,788.308368,0.332792,645.585653,0.398601,(2) Web,(PA) Pennsylvania,(38) Pennsylvania,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(2) Rented for cash,(1) Urban

### Possible Visualization 1

* Comparing how men vs. women answered various opinion questions of Trump vs. Harris
* Comparing how men vs. women view different politicians (who have dynamic views and personal circumstances that may influence opinion) - is there a difference where even if women tend to be more liberal do they still support conservative politicians?
  * Is there a discrepancy between how men/women view issues and how they approve of different politicians?

In [3]:
display(norc_raw.dtypes)

SU_ID                          int64
POLLCLOSE_STATE_WEIGHT       float64
FINALVOTE_STATE_WEIGHT       float64
POLLCLOSE_NATIONAL_WEIGHT    float64
FINALVOTE_NATIONAL_WEIGHT    float64
                              ...
DOGOWNER                      object
TIKTOKUSER                    object
LGBT                          object
HOUSING                       object
SIZEPLACE                     object
Length: 466, dtype: object

# Import SAVE Act Data

Use existing SAVE Act data from CAP, but re-create their estimates of women whose names are different on their birth certificates by using ACS data like they did.

In [4]:
raw_acs_df = pd.read_csv("../data/raw-data/CAP/ACS_sex_by_age.csv")
relevant_cols = [col for col in raw_acs_df.columns if 'Estimate' in col or 'Label' in col]
acs_df = raw_acs_df[relevant_cols]

In [5]:
display(acs_df)

,Label (Grouping),Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,District of Columbia!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"5,157,699","740,133","7,582,384","3,088,354","39,431,263","5,957,494","3,675,069","1,051,917","702,250",...,"7,227,750","31,290,831","3,503,613","648,493","8,811,195","7,958,180","1,769,979","5,960,975","587,618","3,203,295"
1,Male:,"2,490,551","390,301","3,782,883","1,517,526","19,675,103","3,016,719","1,804,896","506,763","332,062",...,"3,544,910","15,608,512","1,778,121","320,167","4,356,641","4,009,969","881,512","2,984,118","301,319","1,516,882"
2,Under 5 years,"141,881","23,437","200,775","89,764","1,061,708","156,618","93,454","26,707","19,495",...,"207,418","991,727","115,953","13,467","245,420","217,786","42,353","154,111","15,266","48,205"
3,5 to 9 years,"161,224","22,605","207,831","97,420","1,159,051","167,233","102,579","28,485","19,365",...,"214,054","1,072,050","126,522","16,647","265,809","237,146","42,945","173,215","15,871","62,986"
4,10 to 14 years,"164,873","27,855","246,928","104,574","1,279,071","180,097","107,177","32,523","17,192",...,"238,684","1,141,156","145,413","15,786","283,971","243,372","57,247","186,403","20,765","83,132"
5,15 to 17 years,"103,995","15,902","153,345","64,562","806,056","117,606","70,697","18,913","9,048",...,"149,058","707,123","93,309","10,411","173,870","153,077","35,519","119,714","14,899","55,370"
6,18 and 19 years,"73,450","10,010","107,786","43,518","544,659","81,757","49,599","12,468","8,739",...,"90,488","460,613","56,325","9,896","130,191","96,960","23,867","79,218","8,326","43,228"
7,20 years,"37,286","5,239","56,003","21,655","269,065","37,515","25,446","6,487","4,295",...,"46,351","215,717","31,034","4,608","59,554","48,669","10,962","40,600","3,862","23,538"
8,21 years,"33,082","5,648","51,119","18,458","277,889","38,676","24,660","6,178","3,293",...,"43,707","221,504","33,032","4,532","59,391","45,141","12,359","37,268","4,503","20,984"
9,22 to 24 years,"96,642","18,642","162,336","63,034","774,037","126,757","74,273","20,636","14,945",...,"156,010","677,225","93,688","12,265","177,899","161,418","32,659","126,666","12,800","59,739"
10,25 to 29 years,"157,413","28,734","269,134","99,535","1,377,449","229,964","117,707","29,632","32,711",...,"238,890","1,120,748","141,977","18,570","283,075","293,015","55,432","191,296","16,422","106,775"
11,30 to 34 years,"166,602","31,037","272,512","99,359","1,537,122","261,223","120,053","34,870","37,052",...,"255,957","1,173,641","130,465","19,765","299,427","332,043","56,348","196,216","19,722","100,236"
12,35 to 39 years,"163,977","30,878","258,707","99,160","1,470,860","233,520","118,515","33,103","31,355",...,"230,688","1,142,488","114,853","20,756","307,242","317,068","54,406","194,367","21,176","90,722"
13,40 to 44 years,"155,700","26,926","245,202","103,425","1,402,460","231,340","120,531","30,173","27,663",...,"231,424","1,136,190","127,007","19,976","309,014","292,252","55,039","191,637","21,376","99,241"
14,45 to 49 years,"145,897","23,528","217,568","89,349","1,224,094","187,517","105,029","27,360","19,563",...,"210,668","980,273","113,195","19,575","266,877","247,472","51,737","177,140","17,638","95,074"
15,50 to 54 years,"156,919","20,445","216,536","89,377","1,214,417","182,820","110,488","28,697","17,565",...,"221,139","935,829","93,644","20,874","269,318","232,761","57,400","174,756","17,178","92,690"
16,55 to 59 years,"149,999","19,161","197,287","85,459","1,156,579","155,116","123,290","30,567","16,781",...,"220,986","826,363","79,901","20,141","253,231","224,296","54,211","183,307","14,653","91,941"
17,60 and 61 years,"64,260","9,545","88,858","35,012","486,359","71,328","48,024","15,299","4,810",...,"93,645","344,732","30,583","7,328","109,716","90,027","24,499","81,665","7,122","43,759"
18,62 to 64 years,"97,018","15,634","141,845","60,517","679,881","102,344","73,200","21,491","10,170",...,"126,159","486,624","45,190","16,834","168,327","142,922","36,524","128,564","12,507","60,121"
19,65 and 66 years,"59,834","9,415","82,005","34,902","423,837","59,700","44,852","13,057","5,187",...,"78,503","297,300","27,349","7,480","96,534","84,197","23,812","81,033","7,721","39,359"
20,67 to 69 years,"83,025","10,336","128,035","46,805","562,091","91,225","62,622","20,942","7,244",...,"113,539","401,993","43,283","14,225","135,566","123,262","34,490","106,505","10,236","54,997"
21,70 to 74 years,"114,607","16,459","175,356","71,107","785,673","132,839","85,748","29,112","9,881",...,"157,825","540,236","55,800","20,030","188,131","178,940","49,001","154,157","18,220","78,631"
22,75 to 79 years,"78,623","10,296","152,268","49,474","570,969","86,461","59,211","20,324","6,773",...,"115,323","370,127","39,626","12,804","136,820","123,058","37,253","101,558","10,924","76,490"
23,80 to 84 years,"50,666","5,012","92,759","30,338","331,708","48,395","37,390","11,554","5,067",...,"61,380","215,048","21,713","8,559","79,840","69,009","20,042","58,225","5,952","48,374"
24,85 years and over,"33,578","3,557","58,688","20,722","280,068","36,668","30,351","8,185","3,868",...,"43,014","149,805","18,259","5,638","57,418","56,078","13,407","46,497","4,180","41,290"
25,Female:,"2,667,148","349,832","3,799,501","1,570,828","19,756,160","2,940,775","1,870,173","545,154","370,188",...,"3,682,840","15,682,319","1,725,492","328,326","4,454,554","3,948,211","888,467","2,976,857","286,299","1,686,413"
26,Under 5 years,"143,877","21,485","193,188","86,835","1,021,446","149,846","86,442","28,081","20,003",...,"202,787","960,022","113,063","13,353","226,094","200,729","44,069","148,933","13,078","42,075"
27,5 to 9 years,"151,589","23,942","207,288","96,835","1,098,448","156,315","93,947","29,229","21,479",...,"203,692","1,031,515","123,628","13,107","248,652","229,515","41,962","163,761","15,627","60,343"
28,10 to 14 years,"164,124","25,224","230,294","95,900","1,221,639","172,571","103,892","30,197","14,138",...,"220,891","1,074,082","128,924","17,966","262,646","229,204","50,927","174,237","19,322","76,987"
29,15 to 17 years,"100,640","13,748","146,102","62,251","763,919","106,561","69,032","19,611","9,298",...,"139,815","679,815","85,941","11,291","167,568","141,220","32,556","112,902","10,158","51,628"
30,18 and 19 years,"80,293","7,503","99,026","42,716","526,566","70,844","52,169","15,225","10,875",...,"84,126","421,724","54,988","10,754","114,032","87,394","21,330","74,525","7,715","38,661"
31,20 years,"37,679","3,321","51,123","20,484","253,230","40,098","22,845","6,012","4,772",...,"48,390","206,540","27,519","5,067","56,008","45,805","9,098","39,506","3,495","21,918"
32,21 years,"34,416","3,247","50,031","19,877","236,424","35,749","21,453","6,443","5,367",...,"46,027","204,432","28,475","4,593","55,415","44,100","13,416","43,610","3,473","25,108"
33,22 to 24 years,"92,587","14,401","149,456","61,801","762,260","114,289","71,393","18,011","18,574",...,"139,694","648,627","92,595","10,403","171,847","145,184","30,021","113,668","9,114","61,328"
34,25 to 29 years,"159,547","24,350","250,767","93,251","1,328,848","216,168","111,979","29,763","40,785",...,"238,768","1,081,395","132,415","17,492","276,812","275,107","48,850","183,043","19,117","99,648"
35,30 to 34 years,"171,785","29,190","255,321","98,378","1,465,318","236,076","118,465","32,883","40,768",...,"259,074","1,138,773","123,477","18,939","300,809","309,648","52,494","186,911","18,550","105,379"
36,35 to 39 years,"166,929","27,692","235,769","102,054","1,378,010","224,613","125,467","34,649","32,375",...,"243,142","1,102,964","117,746","22,144","313,728","293,636","54,282","188,824","19,059","102,655"
37,40 to 44 years,"171,779","22,702","241,378","101,480","1,350,649","203,199","115,039","34,317","29,101",...,"239,877","1,109,999","113,621","19,699","301,525","276,511","52,229","186,576","19,550","102,607"
38,45 to 49 years,"158,555","20,109","215,608","93,385","1,210,681","178,541","110,124","29,853","20,212",...,"215,481","980,204","108,148","19,539","275,216","236,689","54,365","169,986","17,153","106,933"
39,50 to 54 years,"161,976","18,538","219,344","95,037","1,212,268","169,545","114,823","30,365","17,211",...,"228,782","938,073","90,268","18,647","265,957","228,046","55,862","171,452","15,064","107,001"
40,55 to 59 years,"159,736","16,934","212,481","86,875","1,168,622","156,786","122,872","34,253","16,159",...,"230,103","827,869","78,473","19,186","269,268","218,755","55,234","176,191","16,428","108,276"
41,60 and 61 years,"67,466","9,584","97,323","43,389","486,778","73,532","55,480","16,961","6,508",...,"91,948","351,946","31,044","9,328","120,205","97,730","22,978","81,903","7,337","50,909"
42,62 to 64 years,"109,337","13,522","142,955","60,921","700,539","110,966","81,588","24,651","9,909",...,"145,848","533,379","46,275","17,069","172,696","144,974","39,948","137,762","11,919","74,584"
43,65 and 66 years,"67,922","7,020","94,289","40,755","441,712","69,807","49,842","15,501","5,510",...,"86,549","315,447","31,177","8,623","109,893","90,721","26,101","80,921","8,433","44,677"
44,67 to 69 years,"97,859","10,912","141,873","52,489","632,896","99,104","69,866","25,697","9,087",...,"129,738","446,815","43,488","15,157","151,730","135,971","37,309","111,387","10,185","67,828"
45,70 to 74 years,"138,725","16,441","204,740","81,465","905,833","138,033","93,839","31,663","13,941",...,"189,399","629,063","60,469","21,955","219,960","199,175","53,971","165,120","17,150","101,977"
46,75 to 79 years,"108,854","10,211","173,796","63,535","692,829","103,216","74,375","23,105","10,478",...,"136,582","461,914","43,855","15,136","171,551","149,722","43,519","113,734","11,278","102,323"
47,80 to 84 years,"62,400","4,963","106,518","37,666","452,473","59,071","49,466","14,280","8,143",...,"80,183","286,824","25,825","9,587","105,801","87,412","25,061","76,959","7,472","64,947"
48,85 years and over,"59,073","4,793","80,831","33,449","444,772","55,845","55,775","14,404","5,495",...,"81,944","250,897","24,078","9,291","97,141","80,963","22,885","74,946","5,622","68,621"