## Imports

In [16]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

## Read in Data

In [17]:
df = pd.read_csv('Potential Datasets/2025-NPORS-Dataset_FINAL/NPORS_2025_for_public_release_FINAL.csv')
df.head()

,RESPID,MODE,LANGUAGE,LANGUAGEINITIAL,STRATUM,INTERVIEW_START,INTERVIEW_END,ECON1MOD,ECON1BMOD,COMTYPE2,...,BIRTHPLACE,GENDER,ADULTS,VOTED2024,VOTEGEN_POST,INC_SDT1,CREGION,METRO,BASEWT,WEIGHT
0,1470,2,1,NaN,10,2025-05-27,2025-05-27,4,2,3,...,1,2,1,1,2.0,2,4,1,0.802200,0.497038
1,2374,2,1,NaN,7,2025-05-01,2025-05-01,3,2,1,...,1,1,4,1,2.0,5,4,1,0.532494,0.307081
2,1177,3,1,10.0,5,2025-03-04,2025-03-04,2,1,3,...,1,2,2,1,1.0,2,4,1,1.249642,0.646850
3,15459,2,1,NaN,10,2025-05-05,2025-05-05,3,3,3,...,1,1,2,1,1.0,1,2,2,1.604401,1.311245
4,9849,1,1,9.0,9,2025-02-22,2025-02-22,2,1,2,...,1,1,4,1,1.0,8,1,1,0.676351,0.241761

In [18]:
raw_df = df.copy()

In [ ]:
# Clean column names
label_to_var = {
    "case_id": "RESPID",
    "data_collection_mode": "MODE",
    "language_finish": "LANGUAGE",
    "language_start": "LANGUAGEINITIAL",
    "sampling_stratum": "STRATUM",
    "interview_start": "INTERVIEW_START",
    "interview_end": "INTERVIEW_END",

    "econ_conditions_today": "ECON1MOD",
    "econ_conditions_future": "ECON1BMOD",
    "community_type": "COMTYPE2",
    "americans_united_divided": "UNITY",
    "crime_safety": "CRIMESAFE",
    "gov_should_protect_people": "GOVPROTCT",
    "guns_more_or_less_crime": "MOREGUNIMPACT",
    "household_financial_situation": "FIN_SIT",

    "military_service_household": "VET1",
    "volunteered_past_year": "VOL12_CPS",

    "uses_internet": "EMINUSE",
    "internet_mobile_access": "INTMOB",
    "internet_frequency": "INTFREQ",
    "internet_frequency_collapsed": "INTFREQ_COLLAPSED",
    "home_internet_subscription": "HOME4NW2",
    "home_internet_type": "BBHOME",

    "uses_facebook": "SMUSE_FB",
    "uses_youtube": "SMUSE_YT",
    "uses_twitter_x": "SMUSE_X",
    "uses_instagram": "SMUSE_IG",
    "uses_snapchat": "SMUSE_SC",
    "uses_whatsapp": "SMUSE_WA",
    "uses_tiktok": "SMUSE_TT",
    "uses_reddit": "SMUSE_RD",
    "uses_bluesky": "SMUSE_BSK",
    "uses_threads": "SMUSE_TH",
    "uses_truth_social": "SMUSE_TS",

    "listens_radio": "RADIO",
    "has_cellphone": "DEVICE1A",
    "has_smartphone": "SMART2",
    "has_landline": "NHISLL",

    "religion": "RELIG",
    "religion_4cat": "RELIGCAT1",
    "born_again": "BORN",
    "religious_service_attendance": "ATTENDPER",
    "religious_service_online": "ATTENDONLINE2",
    "religion_importance": "RELIMP",
    "prayer_frequency": "PRAY",

    "education_3cat": "EDUCCAT",
    "registered_to_vote": "REGISTRATION",
    "party_id": "PARTY",
    "party_lean": "PARTYLN",
    "party_summary": "PARTYSUM",

    "hispanic_origin": "HISP",
    "race_combined": "RACECMB",
    "race_ethnicity": "RACETHN",

    "age_group": "AGEGRP",
    "age_4cat": "AGECAT",
    "birthplace": "BIRTHPLACE",
    "gender": "GENDER",
    "num_adults_household": "ADULTS",

    "voted_2024": "VOTED2024",
    "vote_choice_2024": "VOTEGEN_POST",

    "family_income": "INC_SDT1",
    "census_region": "CREGION",
    "metro_status": "METRO",

    "base_weight": "BASEWT",
    "final_weight": "WEIGHT"
}

In [20]:
df = df.rename(columns={v: k for k, v in label_to_var.items()})

In [ ]:
# Create value labels for categorical variables
value_labels = {
    "data_collection_mode": {
        1: "Online",
        2: "Paper",
        3: "Phone"
    },

    "econ_conditions_today": {
        1: "Excellent",
        2: "Good",
        3: "Only fair",
        4: "Poor"
    },

    "community_type": {
        1: "Urban",
        2: "Suburban",
        3: "Rural"
    },

    "americans_united_divided": {
        1: "Americans united",
        2: "Americans divided"
    },

    "crime_safety": {
        1: "Extremely safe",
        2: "Very safe",
        3: "Somewhat safe",
        4: "Not too safe",
        5: "Not at all safe"
    },

    "household_financial_situation": {
        1: "Live comfortably",
        2: "Basic expenses + extras",
        3: "Just basic expenses",
        4: "Cannot meet basic expenses"
    },

    "party_summary": {
        1: "Rep / Lean Rep",
        2: "Dem / Lean Dem",
        9: "No lean / DK"
    },

    "gender": {
        1: "Man",
        2: "Woman",
        3: "Other"
    },

    "age_4cat": {
        1: "18-29",
        2: "30-49",
        3: "50-64",
        4: "65+"
    },

    "metro_status": {
        1: "Metropolitan",
        2: "Non-metropolitan"
    }

}

In [22]:
for col, mapping in value_labels.items():
    df[col] = df[col].map(mapping)

In [30]:
df.describe(include='all')

,case_id,data_collection_mode,language_finish,language_start,sampling_stratum,interview_start,interview_end,econ_conditions_today,econ_conditions_future,community_type,...,birthplace,gender,num_adults_household,voted_2024,vote_choice_2024,family_income,census_region,metro_status,base_weight,final_weight
count,5022.000000,5022,5022.000000,2768.000000,5022.000000,5022,5022,5006,5022.000000,4963,...,5022.000000,4997,5022.000000,5022.000000,3973.000000,5022.000000,5022.000000,5022,5022.000000,5022.000000
unique,NaN,3,NaN,NaN,NaN,108,108,4,NaN,3,...,NaN,3,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN
top,NaN,Online,NaN,NaN,NaN,2025-05-05,2025-05-05,Only fair,NaN,Suburban,...,NaN,Woman,NaN,NaN,NaN,NaN,NaN,Metropolitan,NaN,NaN
freq,NaN,2349,NaN,NaN,NaN,642,642,2096,NaN,2334,...,NaN,2758,NaN,NaN,NaN,NaN,NaN,4327,NaN,NaN
mean,9380.612505,NaN,1.034249,9.040824,8.737953,NaN,NaN,NaN,2.198327,NaN,...,2.160295,NaN,5.444644,2.213262,6.000000,8.699920,2.684986,NaN,1.000000,1.000000
std,5488.570583,NaN,0.181887,0.197917,2.398929,NaN,NaN,NaN,4.604762,NaN,...,8.838546,NaN,18.060335,9.909093,20.210984,19.886127,0.989051,NaN,0.592132,0.946622
min,2.000000,NaN,1.000000,9.000000,1.000000,NaN,NaN,NaN,1.000000,NaN,...,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.080082,0.068941
25%,4587.250000,NaN,1.000000,9.000000,9.000000,NaN,NaN,NaN,1.000000,NaN,...,1.000000,NaN,1.000000,1.000000,1.000000,2.000000,2.000000,NaN,0.532494,0.394950
50%,9441.000000,NaN,1.000000,9.000000,10.000000,NaN,NaN,NaN,2.000000,NaN,...,1.000000,NaN,2.000000,1.000000,2.000000,5.000000,3.000000,NaN,0.802200,0.700904
75%,14111.750000,NaN,1.000000,9.000000,10.000000,NaN,NaN,NaN,3.000000,NaN,...,1.000000,NaN,2.000000,1.000000,2.000000,7.000000,3.000000,NaN,1.604401,1.224280
max,18800.000000,NaN,2.000000,10.000000,10.000000,NaN,NaN,NaN,99.000000,NaN,...,99.000000,NaN,99.000000,99.000000,99.000000,99.000000,4.000000,NaN,2.522327,5.454124

In [31]:
df.columns

Index(['case_id', 'data_collection_mode', 'language_finish', 'language_start',
       'sampling_stratum', 'interview_start', 'interview_end',
       'econ_conditions_today', 'econ_conditions_future', 'community_type',
       'americans_united_divided', 'crime_safety', 'gov_should_protect_people',
       'guns_more_or_less_crime', 'household_financial_situation',
       'military_service_household', 'volunteered_past_year', 'uses_internet',
       'internet_mobile_access', 'internet_frequency',
       'internet_frequency_collapsed', 'home_internet_subscription',
       'home_internet_type', 'uses_facebook', 'uses_youtube', 'uses_twitter_x',
       'uses_instagram', 'uses_snapchat', 'uses_whatsapp', 'uses_tiktok',
       'uses_reddit', 'uses_bluesky', 'uses_threads', 'uses_truth_social',
       'listens_radio', 'has_cellphone', 'has_smartphone', 'has_landline',
       'religion', 'religion_4cat', 'born_again',
       'religious_service_attendance', 'religious_service_online',
       'religion_importance', 'prayer_frequency', 'education_3cat',
       'registered_to_vote', 'party_id', 'party_lean', 'party_summary',
       'hispanic_origin', 'race_combined', 'race_ethnicity', 'age_group',
       'age_4cat', 'birthplace', 'gender', 'num_adults_household',
       'voted_2024', 'vote_choice_2024', 'family_income', 'census_region',
       'metro_status', 'base_weight', 'final_weight'],
      dtype='object')

In [38]:
df.groupby(['gender','age_4cat','party_summary']).size()

gender  age_4cat  party_summary
Man     18-29     Dem / Lean Dem     81
                  No lean / DK       16
                  Rep / Lean Rep     84
        30-49     Dem / Lean Dem    263
                  No lean / DK       32
                  Rep / Lean Rep    270
        50-64     Dem / Lean Dem    221
                  No lean / DK       30
                  Rep / Lean Rep    316
        65+       Dem / Lean Dem    370
                  No lean / DK       42
                  Rep / Lean Rep    443
Other   18-29     Dem / Lean Dem     17
                  No lean / DK        1
                  Rep / Lean Rep      1
        30-49     Dem / Lean Dem      8
                  Rep / Lean Rep      4
        50-64     Dem / Lean Dem      7
                  No lean / DK        2
        65+       Dem / Lean Dem      3
                  No lean / DK        2
Woman   18-29     Dem / Lean Dem    172
                  No lean / DK       13
                  Rep / Lean Rep     93
        30-49     Dem / Lean Dem    439
                  No lean / DK       66
                  Rep / Lean Rep    310
        50-64     Dem / Lean Dem    333
                  No lean / DK       54
                  Rep / Lean Rep    309
        65+       Dem / Lean Dem    503
                  No lean / DK       59
                  Rep / Lean Rep    385
dtype: int64

In [40]:
df.groupby(['gender','age_4cat','guns_more_or_less_crime']).size()

gender  age_4cat  guns_more_or_less_crime
Man     18-29     1                           66
                  2                           50
                  3                           65
        30-49     1                          212
                  2                          192
                  3                          159
                  99                           2
        50-64     1                          152
                  2                          227
                  3                          187
                  99                           1
        65+       1                          250
                  2                          287
                  3                          312
                  99                           6
Other   18-29     1                           14
                  3                            5
        30-49     1                            3
                  2                            5
                  3                            4
        50-64     1                            6
                  3                            3
        65+       1                            1
                  2                            1
                  3                            2
                  99                           1
Woman   18-29     1                          164
                  2                           47
                  3                           66
                  99                           1
        30-49     1                          377
                  2                          162
                  3                          270
                  99                           6
        50-64     1                          268
                  2                          167
                  3                          257
                  99                           4
        65+       1                          425
                  2                          186
                  3                          327
                  99                           9
dtype: int64