## Imports

In [2]:
import pandas as pd

## Read in NORC Data

In [3]:
state_df = pd.read_csv('../data/raw-data/NORC/AP_NORC_survey.csv')
state_df.shape

(139938, 466)

In [4]:
state_df.head()

,SU_ID,POLLCLOSE_STATE_WEIGHT,FINALVOTE_STATE_WEIGHT,POLLCLOSE_NATIONAL_WEIGHT,FINALVOTE_NATIONAL_WEIGHT,MODE,P_STATE,STATENUM,LVB,LIKELYVOTER,...,BORNAGAIN,BORNAGAINSTATE,ATTENDANCE,PARENTUS,CATOWNER,DOGOWNER,TIKTOKUSER,LGBT,HOUSING,SIZEPLACE
0,1000001,546.798136,0.357366,442.024098,0.250968,(2) Web,(HI) Hawaii,(11) Hawaii,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(2) No,(1) Yes,(1) Yes,(2) No,(2) Rented for cash,(2) Suburban
1,1000002,139.874024,0.231562,105.968208,0.076913,(2) Web,(ME) Maine,(21) Maine,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(2) No,(2) No,(2) No,(2) No,(2) Rented for cash,(3) Small town
2,1000003,1434.081847,1.508009,1274.137585,0.950696,(2) Web,(MN) Minnesota,(23) Minnesota,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(4) Rural
3,1000004,634.071275,0.380504,512.574504,0.267217,(2) Web,(HI) Hawaii,(11) Hawaii,(5) Already voted,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(2) Suburban
4,1000005,1.241451,0.001997,0.822831,0.000701,(2) Web,(NV) Nevada,(33) Nevada,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(2) Rented for cash,(3) Small town

## Analyze Value Counts for Variables of Interest
- MAGA, PARTY, RELIG, EDUC, SIZEPLACE (urban/rural/suburban status)

In [5]:
state_df.INCOME.value_counts(dropna=False, normalize=True) * 100

INCOME
(5) $100,000 or more                            25.621347
(2) $25,000-$49,999                             22.511398
(3) $50,000-$74,999                             19.452186
(1) Under $25,000                               16.799583
(4) $75,000-$99,999                             14.868728
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)     0.746759
Name: proportion, dtype: float64

In [6]:
state_df.MAGA.value_counts(dropna=False, normalize=True)

MAGA
(2) No                                          0.620611
(1) Yes                                         0.371529
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.007861
Name: proportion, dtype: float64

In [7]:
state_df.PARTY.value_counts(dropna=False, normalize=True)

PARTY
(1) Democrat                                    0.365526
(2) Republican                                  0.346596
(3) Neither                                     0.287420
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.000457
Name: proportion, dtype: float64

In [8]:
state_df.RELIG.value_counts(dropna=False, normalize=True)

RELIG
(8) None                                        0.228630
(1) Protestant                                  0.200582
(2) Catholic                                    0.184382
(4) Other Christian                             0.180065
(7) Something else                              0.078020
(88) REMOVED FOR DISCLOSURE RISK                0.071767
(5) Jewish                                      0.022681
(3) Mormon                                      0.018644
(6) Muslim                                      0.011669
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.003559
Name: proportion, dtype: float64

In [9]:
state_df.SIZEPLACE.value_counts(dropna=False, normalize=True)

SIZEPLACE
(2) Suburban                                    0.408388
(1) Urban                                       0.220212
(4) Rural                                       0.185975
(3) Small town                                  0.181688
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.003737
Name: proportion, dtype: float64

In [10]:
state_df.EDUC.value_counts(dropna=False, normalize=True)

EDUC
(2) Some college/assoc. degree                  0.335634
(1) High school or less                         0.262073
(3) College graduate                            0.232374
(4) Postgraduate study                          0.169304
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.000615
Name: proportion, dtype: float64

In [11]:
state_df.MARRIED.value_counts(dropna=False, normalize=True)

MARRIED
                                                0.698552
(1) Married                                     0.120782
(5) Never married                               0.077491
(88) REMOVED FOR DISCLOSURE RISK                0.044813
(3) Divorced                                    0.034794
(2) Widowed                                     0.016279
(4) Separated                                   0.006796
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.000493
Name: proportion, dtype: float64

In [12]:
state_df.AGE65.value_counts(dropna=False, normalize=True)

AGE65
(6) 65+                                         0.258522
(5) 50-64                                       0.248753
(4) 40-49                                       0.166845
(3) 30-39                                       0.166024
(1) 18-24                                       0.086403
(2) 25-29                                       0.071753
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.001701
Name: proportion, dtype: float64

In [13]:
state_df.RACETH.value_counts(dropna=False, normalize=True)

RACETH
(88) REMOVED FOR DISCLOSURE RISK                 0.539282
(1) White                                        0.316047
(3) Latino or Hispanic                           0.052773
(2) African American or Black                    0.047828
(7) Other                                        0.023811
(4) Asian                                        0.015121
(5) American Indian or Alaska Native             0.003473
(6) Native Hawaiian or Other Pacific Islander    0.000972
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)     0.000693
Name: proportion, dtype: float64

## Read in SAVE Act Tables

In [14]:
save_act_df = pd.read_excel("../data/raw-data/SAVEAct_tables.xlsx")
save_act_df.head()

,State,(15 years and older) whose names do not match their birth certificate (last name change or hyphenation),Female citizens 15 and older who are married or have been married,Estimated number of female citizens whose names do not match their birth certificate (last name change only)
0,Alabama,1153766,1373531,1085090
1,Alaska,155961,185668,146678
2,Arizona,1527920,1818952,1436972
3,Arkansas,697813,830730,656277
4,California,7033264,8372933,6614617

In [15]:
# Clean State Column from NPORS to join
state_df['P_STATE'] = state_df['P_STATE'].str.replace(r'^\([A-Z]{2}\)\s*', '', regex=True)
state_df['P_STATE'].value_counts()

P_STATE
Texas             5778
Florida           5670
California        5644
New York          5115
Arizona           4875
Georgia           4762
Ohio              4675
Pennsylvania      4629
Wisconsin         4567
North Carolina    4417
Michigan          4404
Maryland          4329
Nevada            4099
Minnesota         4016
Colorado          3985
Virginia          3303
Illinois          3224
Indiana           3180
Tennessee         3012
Louisiana         2924
South Carolina    2890
Missouri          2843
Washington        2842
Massachusetts     2801
Kentucky          2714
New Jersey        2687
Oregon            2672
Connecticut       2652
Arkansas          2646
Utah              2401
Iowa              2200
New Mexico        2189
Maine             2136
Nebraska          2051
New Hampshire     2029
Kansas            2014
Alaska            1430
Montana           1375
West Virginia     1181
Alabama           1133
Oklahoma          1108
Mississippi       1065
South Dakota       885
Wyoming            868
Idaho              804
Vermont            797
North Dakota       787
Delaware           750
Hawaii             723
Rhode Island       657
Name: count, dtype: int64

## Read in ACS Population Estimates
- Bring in to get total number of women 15 plus for each state

In [16]:
raw_acs_df = pd.read_csv("../data/raw-data/ACS_sex_by_age.csv")
relevant_cols = [col for col in raw_acs_df.columns if 'Estimate' in col or 'Label' in col]
acs_df = raw_acs_df[relevant_cols]

In [17]:
acs_df.head()

,Label (Grouping),Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,District of Columbia!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"5,157,699","740,133","7,582,384","3,088,354","39,431,263","5,957,494","3,675,069","1,051,917","702,250",...,"7,227,750","31,290,831","3,503,613","648,493","8,811,195","7,958,180","1,769,979","5,960,975","587,618","3,203,295"
1,Male:,"2,490,551","390,301","3,782,883","1,517,526","19,675,103","3,016,719","1,804,896","506,763","332,062",...,"3,544,910","15,608,512","1,778,121","320,167","4,356,641","4,009,969","881,512","2,984,118","301,319","1,516,882"
2,Under 5 years,"141,881","23,437","200,775","89,764","1,061,708","156,618","93,454","26,707","19,495",...,"207,418","991,727","115,953","13,467","245,420","217,786","42,353","154,111","15,266","48,205"
3,5 to 9 years,"161,224","22,605","207,831","97,420","1,159,051","167,233","102,579","28,485","19,365",...,"214,054","1,072,050","126,522","16,647","265,809","237,146","42,945","173,215","15,871","62,986"
4,10 to 14 years,"164,873","27,855","246,928","104,574","1,279,071","180,097","107,177","32,523","17,192",...,"238,684","1,141,156","145,413","15,786","283,971","243,372","57,247","186,403","20,765","83,132"

In [18]:
# Clean column names
acs_df.columns = acs_df.columns.str.replace('!!Estimate', '')

In [19]:
# Find out where female labels start based on index
acs_df[acs_df['Label (Grouping)'].str.contains('Female')].index

Index([25], dtype='int64')

In [20]:
# filter to only female values using index location
female_acs_df = acs_df.iloc[25:]

# drop actual Female: label since we only want the age groups
# use string contains since there are whitespace issues
female_acs_df = female_acs_df[~female_acs_df['Label (Grouping)'].str.contains('Female:')]

# remove ages under 15
female_15_plus_acs_df = female_acs_df[~female_acs_df['Label (Grouping)'].str.contains('Under 5 years|5 to 9 years|10 to 14 years')]
female_15_plus_acs_df.head()

,Label (Grouping),Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
29,15 to 17 years,"100,640","13,748","146,102","62,251","763,919","106,561","69,032","19,611","9,298",...,"139,815","679,815","85,941","11,291","167,568","141,220","32,556","112,902","10,158","51,628"
30,18 and 19 years,"80,293","7,503","99,026","42,716","526,566","70,844","52,169","15,225","10,875",...,"84,126","421,724","54,988","10,754","114,032","87,394","21,330","74,525","7,715","38,661"
31,20 years,"37,679","3,321","51,123","20,484","253,230","40,098","22,845","6,012","4,772",...,"48,390","206,540","27,519","5,067","56,008","45,805","9,098","39,506","3,495","21,918"
32,21 years,"34,416","3,247","50,031","19,877","236,424","35,749","21,453","6,443","5,367",...,"46,027","204,432","28,475","4,593","55,415","44,100","13,416","43,610","3,473","25,108"
33,22 to 24 years,"92,587","14,401","149,456","61,801","762,260","114,289","71,393","18,011","18,574",...,"139,694","648,627","92,595","10,403","171,847","145,184","30,021","113,668","9,114","61,328"

In [21]:
state_cols = [col for col in female_15_plus_acs_df.columns if col != "Label (Grouping)"]

# Remove commas and convert to numeric
female_15_plus_acs_df[state_cols] = (female_15_plus_acs_df[state_cols].replace({",": ""}, regex=True).apply(pd.to_numeric, errors="coerce"))

female_15_over_by_state = (
    female_15_plus_acs_df
    .set_index("Label (Grouping)")[state_cols]
    .sum(axis=0) # get sum across all rows to create 15 plus total per state
    .reset_index()
)

female_15_over_by_state.columns = ["state", "female_15_plus"]

/var/folders/t8/40bpmbs9559ck36zv79hp_b40000gn/T/ipykernel_17662/2211356302.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  female_15_plus_acs_df[state_cols] = (female_15_plus_acs_df[state_cols].replace({",": ""}, regex=True).apply(pd.to_numeric, errors="coerce"))

In [22]:
female_15_over_by_state.head()

        state  female_15_plus
0     Alabama         2207558
1      Alaska          279181
2     Arizona         3168731
3    Arkansas         1291258
4  California        16414627

In [23]:
# merge save act data with female population data to get percent of women (15 +) at risk
merged = save_act_df.merge(female_15_over_by_state,how='left',left_on='State',right_on="state")
merged.drop(columns=['state'], inplace=True)
merged.head()

,State,(15 years and older) whose names do not match their birth certificate (last name change or hyphenation),Female citizens 15 and older who are married or have been married,Estimated number of female citizens whose names do not match their birth certificate (last name change only),female_15_plus
0,Alabama,1153766,1373531,1085090,2207558.0
1,Alaska,155961,185668,146678,279181.0
2,Arizona,1527920,1818952,1436972,3168731.0
3,Arkansas,697813,830730,656277,1291258.0
4,California,7033264,8372933,6614617,16414627.0

In [24]:
merged.rename(columns={'(15 years and older) whose names do not match their birth certificate (last name change or hyphenation)':'15_plus_name_mismatch'}, inplace=True)

In [25]:
merged['percent_women_at_risk'] = (merged['15_plus_name_mismatch'] / merged['female_15_plus']) * 100
merged[['State','15_plus_name_mismatch','female_15_plus','percent_women_at_risk']].head()

        State  15_plus_name_mismatch  female_15_plus  percent_women_at_risk
0     Alabama                1153766       2207558.0              52.264357
1      Alaska                 155961        279181.0              55.863759
2     Arizona                1527920       3168731.0              48.218672
3    Arkansas                 697813       1291258.0              54.041330
4  California                7033264      16414627.0              42.847541

#### Filter original NORC dataframe to women only

In [26]:
women_df = state_df[state_df['GENDER'] == '(2) Women'].copy()

## Create Flag Columns for Scatterplots

In [27]:
women_df['income_under_25000'] = women_df['INCOME'].isin(['(1) Under $25,000']).astype(int)
women_df['income_above_100000'] = women_df['INCOME'].isin(['(5) $100,000 or more']).astype(int)

In [28]:
# downselect relevant columns for state-level analysis
women_df = women_df[['P_STATE', 'MAGA', 'PARTY', 'RELIG', 'EDUC', 'SIZEPLACE','INCOME','income_above_100000','income_under_25000',
                     'RACE0_VOTE','AGE65']].copy()

In [29]:
# create binary cols for each variable to calculate percentages at state level
women_df['is_maga'] = women_df['MAGA'].eq('(1) Yes').astype(int)

women_df['is_any_religion'] = ~women_df['RELIG'].isin([
    '(8) None',
    '(99) DON\'T KNOW/SKIPPED ON WEB/REFUSED (VOL)',
    '(88) REMOVED FOR DISCLOSURE RISK'
])

women_df['is_any_religion'] = women_df['is_any_religion'].astype(int)

women_df['is_christian'] = women_df['RELIG'].isin([
    '(1) Protestant',
    '(2) Catholic',
    '(3) Mormon',
    '(4) Other Christian'
]).astype(int)

women_df['is_college_ed'] = women_df['EDUC'].isin(["(3) College graduate",'(4) Postgraduate study']).astype(int)
women_df['less_than_bachelors'] = (~women_df['EDUC'].isin(["(3) College graduate",'(4) Postgraduate study'])).astype(int)

women_df['is_rural'] = women_df['SIZEPLACE'].isin(['(4) Rural','(3) Small town']).astype(int)
women_df['is_urban'] = women_df['SIZEPLACE'].isin(['(1) Urban']).astype(int)
women_df['is_suburban'] = women_df['SIZEPLACE'].isin(['(2) Suburban']).astype(int)
women_df['under_30'] = women_df['AGE65'].isin(['(1) 18-24','(2) 25-29']).astype(int)

In [30]:
women_df['voted_trump'] = women_df['RACE0_VOTE'].isin(['(8639) Donald Trump']).astype(int)
women_df['is_republican'] = women_df['PARTY'].isin(['(2) Republican']).astype(int)

In [31]:
# group by state and calculate percentages for each variable
state_grouped = (
    women_df.groupby('P_STATE')
    .agg(
        pct_maga=('is_maga', 'mean'),
        pct_christian=('is_christian', 'mean'),
        pct_college_ed=('is_college_ed', 'mean'),
        pct_any_religion = ('is_any_religion','mean'),
        pct_rural=('is_rural', 'mean'),
        pct_urban = ('is_urban','mean'),
        pct_suburban = ('is_suburban','mean'),
        pct_less_than_bachelors = ('less_than_bachelors','mean'),
        pct_income_under_25000 = ('income_under_25000','mean'),
        pct_income_above_10000 = ('income_above_100000','mean'),
        pct_republican = ('is_republican','mean'),
        pct_voted_trump = ('voted_trump','mean'),
        pct_under_30 = ('under_30','mean'),
        n=('P_STATE', 'size') # number of survey responses
    )
    .reset_index()
)

# multiply by 100 for percentage view
cols = ['pct_republican', 'pct_voted_trump', 'pct_income_under_25000',
        'pct_income_above_10000','pct_under_30',
        'pct_maga', 
        'pct_christian', 'pct_any_religion','pct_less_than_bachelors',
        'pct_college_ed','pct_rural','pct_urban','pct_suburban']

state_grouped[cols] = round(state_grouped[cols] * 100,2)

In [32]:
# merge NORC data with save act + ACS combined data on State
state_grouped_merged = state_grouped.merge(merged[['State','15_plus_name_mismatch','female_15_plus','percent_women_at_risk']], how='left', left_on='P_STATE', right_on='State')
state_grouped_merged.drop(columns=['State'], inplace=True)
state_grouped_merged['percent_women_at_risk'] = round(state_grouped_merged['percent_women_at_risk'],2)
state_grouped_merged.head()

,P_STATE,pct_maga,pct_christian,pct_college_ed,pct_any_religion,pct_rural,pct_urban,pct_suburban,pct_less_than_bachelors,pct_income_under_25000,pct_income_above_10000,pct_republican,pct_voted_trump,pct_under_30,n,15_plus_name_mismatch,female_15_plus,percent_women_at_risk
0,Alabama,54.67,72.44,23.11,83.41,54.22,14.96,30.81,76.89,28.00,9.33,48.59,52.74,14.67,675,1153766,2207558.0,52.26
1,Alaska,31.06,0.00,47.94,0.00,48.65,22.41,28.09,52.06,13.90,33.62,27.23,38.58,13.76,705,155961,279181.0,55.86
2,Arizona,34.79,62.76,36.84,74.53,26.22,27.37,45.97,63.16,17.16,21.98,34.31,40.70,14.33,2693,1527920,3168731.0,48.22
3,Arkansas,48.70,70.33,29.18,83.50,61.39,14.56,23.63,70.82,27.98,13.05,40.54,51.30,17.52,1655,697813,1291258.0,54.04
4,California,30.11,59.54,35.67,73.06,22.25,29.32,47.95,64.33,18.59,24.80,26.25,30.94,19.01,2899,7033264,16414627.0,42.85

In [33]:
# Clean column names before plotting
# Capitalize & replace underscores with spaces
state_grouped_merged.columns = state_grouped_merged.columns.str.replace('_', ' ').str.replace('pct','Percent').str.title()
state_grouped_merged = state_grouped_merged.rename(columns={'P State': 'State'})

In [34]:
# make column names more user friendly
state_grouped_merged.rename(columns={
    'Percent Women At Risk': 'Percent of Women At Risk',
    'Percent Republican': 'Percent of Women Who Identify as Republican',
    'Percent Maga': 'Percent of Women Who Identify as MAGA',
    'Percent Rural': 'Percent of Women Living in Rural Areas',
    'Percent Voted Trump': 'Percent of Women Who Voted Trump',
    'Percent Christian': 'Percent of Women Who Identify as Christian',
    'Percent Less Than Bachelors': 'Percent of Women with Less than a College Degree',
    'Percent Maga': 'Percent of Women Who Voted Trump in 2020',
    'Percent Income Under 25000': 'Percent of Women with an Income Under 25000',
    'Percent Under 30':'Percent of Women Under 30'
}, inplace=True)

In [35]:
# temporarily exclude Delaware due to outlier status
plot_df = state_grouped_merged[state_grouped_merged["State"] != "Delaware"].copy()

In [37]:
# Loop over pairs and create scatterplots colored by percent at risk (Excluding Delaware as outlier)
pairs = [
    ('Percent of Women At Risk', 'Percent of Women Living in Rural Areas'),
    ('Percent of Women At Risk','Percent of Women Who Identify as Republican'),
    # ('Percent of Women with an Income Under 25000', 'Percent of Women with Less than a College Degree'),
    # ('Percent of Women At Risk','Percent of Women with Less than a College Degree'),
    # ('Percent of Women At Risk','Percent of Women with an Income Under 25000'),
    # ('Percent of Women At Risk','Percent of Women Who Identify as Christian'),
    # ('Percent of Women At Risk','Percent of Women Under 30'),
]

import plotly.express as px

for x_var, y_var in pairs:
    fig = px.scatter(
        plot_df,
        x=x_var,
        y=y_var,
        width=1000, height=600,
        color='Percent of Women At Risk',
        color_continuous_scale='algae',
        size='N', # size by female 15 + population
        hover_name='State',
        title=f'{y_var} vs {x_var} by State',
        subtitle='Colored by the percentage of women in each state with name mismatches, sized by the number of survey responses'
    )

    fig.update_traces(
        text=state_grouped_merged['State'],
        textposition='top center'
    )

    fig.update_xaxes(title_font_family="Arial")

    fig.show()

    # create safe strings for chart names
    safe_x_var = x_var.replace(' ', '_')
    safe_y_var = y_var.replace(' ', '_')
    fig.write_html(f"../charts/{safe_x_var}_vs_{safe_y_var}.html")

#### Massachusetts vs. West Virginia Visual

In [39]:
highlight_states = ["Massachusetts", "West Virginia"]

background_df = plot_df[~plot_df["State"].isin(highlight_states)]
highlight_df = plot_df[plot_df["State"].isin(highlight_states)]

# highlight Mass and WV using % at risk color
highlight_fig = px.scatter(
    highlight_df,
    x="Percent of Women At Risk",
    y="Percent of Women Living in Rural Areas",
    width=800,
    height=600,
    color="Percent of Women At Risk",
    size="N",
    text="State",
)

# background states in gray
fig = px.scatter(
    background_df,
    x="Percent of Women At Risk",
    y="Percent of Women Living in Rural Areas",
    width=800,
    height=600,
    size="N",
    title="Percent of Women Living in Rural Areas vs Percent of Women At Risk by State",
    subtitle='Colored by the percentage of women in each state with name mismatches, sized by the number of survey responses'
)

fig.update_traces(
    marker=dict(color="lightgray", opacity=0.5),
    showlegend=False
)

# suppress hover info
fig.update_traces(hoverinfo='skip', hovertemplate=None)

for trace in highlight_fig.data:
    fig.add_trace(trace)

fig.update_traces(textposition="top center", selector=dict(mode="markers+text"))
fig.update_xaxes(title_font_family="Arial")
# force colorscale
fig.update_layout(coloraxis={"colorscale": "algae"})

fig.show()

fig.write_html("../charts/Massachusetts_vs_West_Virginia.html")

In [39]:
# save state df to csv for Tableau
state_grouped_merged.to_csv('../data/clean-data/state_data_for_tableau.csv',index=False)