## Imports

In [1]:
import pandas as pd

## Read in NORC Data

In [2]:
state_df = pd.read_csv('../data/raw-data/NORC/AP_NORC_survey.csv')
state_df.shape

(139938, 466)

## Analyze Value Counts for Variables of Interest
- MAGA, PARTY, RELIG, EDUC, SIZEPLACE (urban/rural/suburban status)

In [3]:
state_df.MAGA.value_counts(dropna=False, normalize=True)

MAGA
(2) No                                          0.620611
(1) Yes                                         0.371529
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.007861
Name: proportion, dtype: float64

In [4]:
state_df.PARTY.value_counts(dropna=False, normalize=True)

PARTY
(1) Democrat                                    0.365526
(2) Republican                                  0.346596
(3) Neither                                     0.287420
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.000457
Name: proportion, dtype: float64

In [5]:
state_df.RELIG.value_counts(dropna=False, normalize=True)

RELIG
(8) None                                        0.228630
(1) Protestant                                  0.200582
(2) Catholic                                    0.184382
(4) Other Christian                             0.180065
(7) Something else                              0.078020
(88) REMOVED FOR DISCLOSURE RISK                0.071767
(5) Jewish                                      0.022681
(3) Mormon                                      0.018644
(6) Muslim                                      0.011669
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.003559
Name: proportion, dtype: float64

In [6]:
state_df.SIZEPLACE.value_counts(dropna=False, normalize=True)

SIZEPLACE
(2) Suburban                                    0.408388
(1) Urban                                       0.220212
(4) Rural                                       0.185975
(3) Small town                                  0.181688
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.003737
Name: proportion, dtype: float64

In [7]:
state_df.EDUC.value_counts(dropna=False, normalize=True)

EDUC
(2) Some college/assoc. degree                  0.335634
(1) High school or less                         0.262073
(3) College graduate                            0.232374
(4) Postgraduate study                          0.169304
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.000615
Name: proportion, dtype: float64

In [8]:
state_df.MARRIED.value_counts(dropna=False, normalize=True)

MARRIED
                                                0.698552
(1) Married                                     0.120782
(5) Never married                               0.077491
(88) REMOVED FOR DISCLOSURE RISK                0.044813
(3) Divorced                                    0.034794
(2) Widowed                                     0.016279
(4) Separated                                   0.006796
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)    0.000493
Name: proportion, dtype: float64

## Read in SAVE Act Tables

In [9]:
save_act_df = pd.read_excel("../data/raw-data/SAVEAct_tables.xlsx")
save_act_df.head()

,State,(15 years and older) whose names do not match their birth certificate (last name change or hyphenation),Female citizens 15 and older who are married or have been married,Estimated number of female citizens whose names do not match their birth certificate (last name change only)
0,Alabama,1153766,1373531,1085090
1,Alaska,155961,185668,146678
2,Arizona,1527920,1818952,1436972
3,Arkansas,697813,830730,656277
4,California,7033264,8372933,6614617

In [10]:
# Clean State Column from NPORS to join
state_df['P_STATE'] = state_df['P_STATE'].str.replace(r'^\([A-Z]{2}\)\s*', '', regex=True)
state_df['P_STATE'].value_counts()

P_STATE
Texas             5778
Florida           5670
California        5644
New York          5115
Arizona           4875
Georgia           4762
Ohio              4675
Pennsylvania      4629
Wisconsin         4567
North Carolina    4417
Michigan          4404
Maryland          4329
Nevada            4099
Minnesota         4016
Colorado          3985
Virginia          3303
Illinois          3224
Indiana           3180
Tennessee         3012
Louisiana         2924
South Carolina    2890
Missouri          2843
Washington        2842
Massachusetts     2801
Kentucky          2714
New Jersey        2687
Oregon            2672
Connecticut       2652
Arkansas          2646
Utah              2401
Iowa              2200
New Mexico        2189
Maine             2136
Nebraska          2051
New Hampshire     2029
Kansas            2014
Alaska            1430
Montana           1375
West Virginia     1181
Alabama           1133
Oklahoma          1108
Mississippi       1065
South Dakota       885
Wyoming            868
Idaho              804
Vermont            797
North Dakota       787
Delaware           750
Hawaii             723
Rhode Island       657
Name: count, dtype: int64

## Read in ACS Population Estimates
- Bring in to get total number of women 15 plus for each state

In [11]:
raw_acs_df = pd.read_csv("../data/raw-data/ACS_sex_by_age.csv")
relevant_cols = [col for col in raw_acs_df.columns if 'Estimate' in col or 'Label' in col]
acs_df = raw_acs_df[relevant_cols]

In [12]:
acs_df.head()

,Label (Grouping),Alabama!!Estimate,Alaska!!Estimate,Arizona!!Estimate,Arkansas!!Estimate,California!!Estimate,Colorado!!Estimate,Connecticut!!Estimate,Delaware!!Estimate,District of Columbia!!Estimate,...,Tennessee!!Estimate,Texas!!Estimate,Utah!!Estimate,Vermont!!Estimate,Virginia!!Estimate,Washington!!Estimate,West Virginia!!Estimate,Wisconsin!!Estimate,Wyoming!!Estimate,Puerto Rico!!Estimate
0,Total:,"5,157,699","740,133","7,582,384","3,088,354","39,431,263","5,957,494","3,675,069","1,051,917","702,250",...,"7,227,750","31,290,831","3,503,613","648,493","8,811,195","7,958,180","1,769,979","5,960,975","587,618","3,203,295"
1,Male:,"2,490,551","390,301","3,782,883","1,517,526","19,675,103","3,016,719","1,804,896","506,763","332,062",...,"3,544,910","15,608,512","1,778,121","320,167","4,356,641","4,009,969","881,512","2,984,118","301,319","1,516,882"
2,Under 5 years,"141,881","23,437","200,775","89,764","1,061,708","156,618","93,454","26,707","19,495",...,"207,418","991,727","115,953","13,467","245,420","217,786","42,353","154,111","15,266","48,205"
3,5 to 9 years,"161,224","22,605","207,831","97,420","1,159,051","167,233","102,579","28,485","19,365",...,"214,054","1,072,050","126,522","16,647","265,809","237,146","42,945","173,215","15,871","62,986"
4,10 to 14 years,"164,873","27,855","246,928","104,574","1,279,071","180,097","107,177","32,523","17,192",...,"238,684","1,141,156","145,413","15,786","283,971","243,372","57,247","186,403","20,765","83,132"

In [13]:
# Clean column names
acs_df.columns = acs_df.columns.str.replace('!!Estimate', '')

In [14]:
# Find out where female labels start based on index
acs_df[acs_df['Label (Grouping)'].str.contains('Female')].index

Index([25], dtype='int64')

In [15]:
# filter to only female values using index location
female_acs_df = acs_df.iloc[25:]

# drop actual Female: label since we only want the age groups
# use string contains since there are whitespace issues
female_acs_df = female_acs_df[~female_acs_df['Label (Grouping)'].str.contains('Female:')]

# remove ages under 15
female_15_plus_acs_df = female_acs_df[~female_acs_df['Label (Grouping)'].str.contains('Under 5 years|5 to 9 years|10 to 14 years')]
female_15_plus_acs_df.head()

,Label (Grouping),Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,District of Columbia,...,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming,Puerto Rico
29,15 to 17 years,"100,640","13,748","146,102","62,251","763,919","106,561","69,032","19,611","9,298",...,"139,815","679,815","85,941","11,291","167,568","141,220","32,556","112,902","10,158","51,628"
30,18 and 19 years,"80,293","7,503","99,026","42,716","526,566","70,844","52,169","15,225","10,875",...,"84,126","421,724","54,988","10,754","114,032","87,394","21,330","74,525","7,715","38,661"
31,20 years,"37,679","3,321","51,123","20,484","253,230","40,098","22,845","6,012","4,772",...,"48,390","206,540","27,519","5,067","56,008","45,805","9,098","39,506","3,495","21,918"
32,21 years,"34,416","3,247","50,031","19,877","236,424","35,749","21,453","6,443","5,367",...,"46,027","204,432","28,475","4,593","55,415","44,100","13,416","43,610","3,473","25,108"
33,22 to 24 years,"92,587","14,401","149,456","61,801","762,260","114,289","71,393","18,011","18,574",...,"139,694","648,627","92,595","10,403","171,847","145,184","30,021","113,668","9,114","61,328"

In [16]:
state_cols = [col for col in female_15_plus_acs_df.columns if col != "Label (Grouping)"]

# Remove commas and convert to numeric
female_15_plus_acs_df[state_cols] = (female_15_plus_acs_df[state_cols].replace({",": ""}, regex=True).apply(pd.to_numeric, errors="coerce"))

female_15_over_by_state = (
    female_15_plus_acs_df
    .set_index("Label (Grouping)")[state_cols]
    .sum(axis=0) # get sum across all rows to create 15 plus total per state
    .reset_index()
)

female_15_over_by_state.columns = ["state", "female_15_plus"]

/var/folders/t8/40bpmbs9559ck36zv79hp_b40000gn/T/ipykernel_34544/2211356302.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  female_15_plus_acs_df[state_cols] = (female_15_plus_acs_df[state_cols].replace({",": ""}, regex=True).apply(pd.to_numeric, errors="coerce"))

In [17]:
female_15_over_by_state.head()

        state  female_15_plus
0     Alabama         2207558
1      Alaska          279181
2     Arizona         3168731
3    Arkansas         1291258
4  California        16414627

In [18]:
# merge save act data with female population data to get percent of women (15 +) at risk
merged = save_act_df.merge(female_15_over_by_state,how='left',left_on='State',right_on="state")
merged.drop(columns=['state'], inplace=True)
merged.head()

,State,(15 years and older) whose names do not match their birth certificate (last name change or hyphenation),Female citizens 15 and older who are married or have been married,Estimated number of female citizens whose names do not match their birth certificate (last name change only),female_15_plus
0,Alabama,1153766,1373531,1085090,2207558.0
1,Alaska,155961,185668,146678,279181.0
2,Arizona,1527920,1818952,1436972,3168731.0
3,Arkansas,697813,830730,656277,1291258.0
4,California,7033264,8372933,6614617,16414627.0

In [19]:
merged.rename(columns={'(15 years and older) whose names do not match their birth certificate (last name change or hyphenation)':'15_plus_name_mismatch'}, inplace=True)

In [20]:
merged['percent_women_at_risk'] = (merged['15_plus_name_mismatch'] / merged['female_15_plus']) * 100
merged[['State','15_plus_name_mismatch','female_15_plus','percent_women_at_risk']].head()

        State  15_plus_name_mismatch  female_15_plus  percent_women_at_risk
0     Alabama                1153766       2207558.0              52.264357
1      Alaska                 155961        279181.0              55.863759
2     Arizona                1527920       3168731.0              48.218672
3    Arkansas                 697813       1291258.0              54.041330
4  California                7033264      16414627.0              42.847541

#### Filter original NORC dataframe to women only

In [21]:
women_df = state_df[state_df['GENDER'] == '(2) Women'].copy()

## Create Flag Columns for Scatterplots

In [35]:
# downselect relevant columns for state-level analysis
women_df = women_df[['P_STATE', 'MAGA', 'PARTY', 'RELIG', 'EDUC', 'SIZEPLACE']].copy()

# create binary cols for each variable to calculate percentages at state level
women_df['is_maga'] = women_df['MAGA'].eq('(1) Yes').astype(int)

women_df['is_any_religion'] = ~women_df['RELIG'].isin([
    '(8) None',
    '(99) DON\'T KNOW/SKIPPED ON WEB/REFUSED (VOL)',
    '(88) REMOVED FOR DISCLOSURE RISK'
])

women_df['is_any_religion'] = women_df['is_any_religion'].astype(int)

women_df['is_christian'] = women_df['RELIG'].isin([
    '(1) Protestant',
    '(2) Catholic',
    '(3) Mormon',
    '(4) Other Christian'
]).astype(int)

women_df['is_college_ed'] = women_df['EDUC'].isin(["(3) College graduate",'(4) Postgraduate study']).astype(int)
women_df['less_than_bachelors'] = (~women_df['EDUC'].isin(["(3) College graduate",'(4) Postgraduate study'])).astype(int)

women_df['is_rural'] = women_df['SIZEPLACE'].isin(['(4) Rural','(3) Small town']).astype(int)
women_df['is_urban'] = women_df['SIZEPLACE'].isin(['(1) Urban']).astype(int)
women_df['is_suburban'] = women_df['SIZEPLACE'].isin(['(2) Suburban']).astype(int)

# group by state and calculate percentages for each variable
state_grouped = (
    women_df.groupby('P_STATE')
    .agg(
        pct_maga=('is_maga', 'mean'),
        pct_christian=('is_christian', 'mean'),
        pct_college_ed=('is_college_ed', 'mean'),
        pct_any_religion = ('is_any_religion','mean'),
        pct_rural=('is_rural', 'mean'),
        pct_urban = ('is_urban','mean'),
        pct_suburban = ('is_suburban','mean'),
        pct_less_than_bachelors = ('less_than_bachelors','mean'),
        n=('P_STATE', 'size') # number of survey responses
    )
    .reset_index()
)

# multiply by 100 for percentage view
cols = ['pct_maga', 'pct_christian', 'pct_any_religion','pct_less_than_bachelors','pct_college_ed','pct_rural','pct_urban','pct_suburban']
state_grouped[cols] = round(state_grouped[cols] * 100,2)

In [36]:
state_grouped.head()

,P_STATE,pct_maga,pct_christian,pct_college_ed,pct_any_religion,pct_rural,pct_urban,pct_suburban,pct_less_than_bachelors,n
0,Alabama,54.67,72.44,23.11,83.41,54.22,14.96,30.81,76.89,675
1,Alaska,31.06,0.00,47.94,0.00,48.65,22.41,28.09,52.06,705
2,Arizona,34.79,62.76,36.84,74.53,26.22,27.37,45.97,63.16,2693
3,Arkansas,48.70,70.33,29.18,83.50,61.39,14.56,23.63,70.82,1655
4,California,30.11,59.54,35.67,73.06,22.25,29.32,47.95,64.33,2899

In [37]:
# merge NORC data with save act + ACS combined data on State
state_grouped_merged = state_grouped.merge(merged[['State','15_plus_name_mismatch','female_15_plus','percent_women_at_risk']], how='left', left_on='P_STATE', right_on='State')
state_grouped_merged.drop(columns=['State'], inplace=True)
state_grouped_merged['percent_women_at_risk'] = round(state_grouped_merged['percent_women_at_risk'],2)
state_grouped_merged.head()

,P_STATE,pct_maga,pct_christian,pct_college_ed,pct_any_religion,pct_rural,pct_urban,pct_suburban,pct_less_than_bachelors,n,15_plus_name_mismatch,female_15_plus,percent_women_at_risk
0,Alabama,54.67,72.44,23.11,83.41,54.22,14.96,30.81,76.89,675,1153766,2207558.0,52.26
1,Alaska,31.06,0.00,47.94,0.00,48.65,22.41,28.09,52.06,705,155961,279181.0,55.86
2,Arizona,34.79,62.76,36.84,74.53,26.22,27.37,45.97,63.16,2693,1527920,3168731.0,48.22
3,Arkansas,48.70,70.33,29.18,83.50,61.39,14.56,23.63,70.82,1655,697813,1291258.0,54.04
4,California,30.11,59.54,35.67,73.06,22.25,29.32,47.95,64.33,2899,7033264,16414627.0,42.85

In [38]:
# Clean column names before plotting
# Capitalize & replace underscores with spaces
state_grouped_merged.columns = state_grouped_merged.columns.str.replace('_', ' ').str.replace('pct','Percent').str.title()
state_grouped_merged = state_grouped_merged.rename(columns={'P State': 'State'})

In [39]:
state_grouped_merged.columns

Index(['State', 'Percent Maga', 'Percent Christian', 'Percent College Ed',
       'Percent Any Religion', 'Percent Rural', 'Percent Urban',
       'Percent Suburban', 'Percent Less Than Bachelors', 'N',
       '15 Plus Name Mismatch', 'Female 15 Plus', 'Percent Women At Risk'],
      dtype='object')

In [40]:
# temporarily exclude Delaware due to outlier status
plot_df = state_grouped_merged[state_grouped_merged["State"] != "Delaware"].copy()

In [41]:
# Loop over pairs and create scatterplots colored by percent at risk (Excluding Delaware as outlier)
pairs = [('Percent Rural', 'Percent Christian'),
    ('Percent Less Than Bachelors', 'Percent Maga'),
    ('Percent Urban', 'Percent College Ed'),
    ('Percent Suburban', 'Percent College Ed')]

import plotly.express as px

for x_var, y_var in pairs:
    fig = px.scatter(
        plot_df,
        x=x_var,
        y=y_var,
        color='Percent Women At Risk',
        color_continuous_scale='Bluered',
        size='Female 15 Plus', # size by female 15 + population
        hover_name='State',
        title=f'{y_var} vs {x_var}',
        subtitle='Colored by the number of women with name mismatches, sized by the number of women 15 or older'
    )

    fig.update_traces(
        text=state_grouped_merged['State'],
        textposition='top center'
    )

    fig.show()