In [1]:
import pandas as pd

In [4]:
state_df = pd.read_csv('../data/31122410.csv')
state_df.shape

(139938, 466)

In [8]:
state_df.columns

Index(['SU_ID', 'POLLCLOSE_STATE_WEIGHT', 'FINALVOTE_STATE_WEIGHT',
       'POLLCLOSE_NATIONAL_WEIGHT', 'FINALVOTE_NATIONAL_WEIGHT', 'MODE',
       'P_STATE', 'STATENUM', 'LVB', 'LIKELYVOTER',
       ...
       'BORNAGAIN', 'BORNAGAINSTATE', 'ATTENDANCE', 'PARENTUS', 'CATOWNER',
       'DOGOWNER', 'TIKTOKUSER', 'LGBT', 'HOUSING', 'SIZEPLACE'],
      dtype='object', length=466)

In [9]:
state_df.head()

,SU_ID,POLLCLOSE_STATE_WEIGHT,FINALVOTE_STATE_WEIGHT,POLLCLOSE_NATIONAL_WEIGHT,FINALVOTE_NATIONAL_WEIGHT,MODE,P_STATE,STATENUM,LVB,LIKELYVOTER,...,BORNAGAIN,BORNAGAINSTATE,ATTENDANCE,PARENTUS,CATOWNER,DOGOWNER,TIKTOKUSER,LGBT,HOUSING,SIZEPLACE
0,1000001,546.798136,0.357366,442.024098,0.250968,(2) Web,(HI) Hawaii,(11) Hawaii,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(2) No,(1) Yes,(1) Yes,(2) No,(2) Rented for cash,(2) Suburban
1,1000002,139.874024,0.231562,105.968208,0.076913,(2) Web,(ME) Maine,(21) Maine,(1) Definitely will vote,(1) Likely voter,...,(2) No,(2) No,,(2) No,(2) No,(2) No,(2) No,(2) No,(2) Rented for cash,(3) Small town
2,1000003,1434.081847,1.508009,1274.137585,0.950696,(2) Web,(MN) Minnesota,(23) Minnesota,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(4) Rural
3,1000004,634.071275,0.380504,512.574504,0.267217,(2) Web,(HI) Hawaii,(11) Hawaii,(5) Already voted,(1) Likely voter,...,,,,,,,,,(1) Owned or being bought by you or someone in...,(2) Suburban
4,1000005,1.241451,0.001997,0.822831,0.000701,(2) Web,(NV) Nevada,(33) Nevada,(1) Definitely will vote,(1) Likely voter,...,,,,,,,,,(2) Rented for cash,(3) Small town

In [11]:
if 'GENDER' in state_df.columns:
    print("GENDER column exists in the DataFrame.")

if 'BUDGETFOOD' in state_df.columns:
    print("BUDGETFOOD column exists in the DataFrame.")

GENDER column exists in the DataFrame.
BUDGETFOOD column exists in the DataFrame.

In [17]:
state_df['BUDGETFOOD'].value_counts()

BUDGETFOOD
(1) Very concerned                              92088
(2) Somewhat concerned                          33963
(3) Not too concerned                           10624
(4) Not at all concerned                         2506
(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL)      757
Name: count, dtype: int64

In [25]:
state_df.groupby(['GENDER','AGE65','BUDGETFOOD']).size().to_frame(name='count').reset_index()

,GENDER,AGE65,BUDGETFOOD,count
0,(1) Men,(1) 18-24,(1) Very concerned,2941
1,(1) Men,(1) 18-24,(2) Somewhat concerned,1341
2,(1) Men,(1) 18-24,(3) Not too concerned,466
3,(1) Men,(1) 18-24,(4) Not at all concerned,127
4,(1) Men,(1) 18-24,(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),41
...,...,...,...,...
114,(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(6) 65+,(2) Somewhat concerned,8
115,(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(6) 65+,(3) Not too concerned,3
116,(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(1) Very concerned,8
117,(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(2) Somewhat concerned,7
118,(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(99) DON'T KNOW/SKIPPED ON WEB/REFUSED (VOL),(4) Not at all concerned,1